### ISSUE TITLE
TypeError: Cannot read property 'textContent' of null when querying certain threads

### ISSUE THREAD

**Issue by mstan** [TheArmagan/4chan-full#3] opened 2020-11-22 07:06 UTC
Expected behavior:

Calling getThread() should return thread.

Actual behavior:

Calling getThread() with arguments "pol",292289046 returns the following error.

TypeError: Cannot read property 'textContent' of null
at result.posts.Array.from.map.e (/Users/matthewstanley/Development/4chan-monitor/node_modules/4chan-full/getThread.js:14:105)
at Array.map (<anonymous>)
at parseBody (/Users/matthewstanley/Development/4chan-monitor/node_modules/4chan-full/getThread.js:12:72)
at Object.getThread (/Users/matthewstanley/Development/4chan-monitor/node_modules/4chan-full/getThread.js:43:20)
at process._tickCallback (internal/process/next_tick.js:68:7)

Can't reproduce with all threads. Provided ID consistently reproduces.

**Comment by TheArmagan** [comment] 2020-12-24 19:01
Sory for long delay.
Currently i can't reproduce the error, if again happens please send board and thread to here.

**Comment by TheArmagan** [comment] 2021-01-28 22:12
ok i am closing it

**Closed as completed by TheArmagan** 2021-01-28 22:12 UTC
Labels: bug
